name = "Server Del Grupito"
author = "El grupito (creo)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb0ce1c1ed30176ab0c698a3e29bdf822aeff366ce3894c1f075d4f97872e406"

[versions]
minecraft = "1.19.2"
quilt = "0.20.0-beta.4"
