name = "Server Del Grupito"
author = "El grupito (creo)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d128f3a7fba65e7c9f16c7e9eb53dfef54ad49afeb377eb56e036baabd9ccb8"

[versions]
minecraft = "1.19.2"
quilt = "0.20.0-beta.4"
