name = "Server Del Grupito"
author = "El grupito (creo)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab0ef84c3e04704f29581a83f57990f04b274a6b57fe16d3d63467bb0671fd26"

[versions]
minecraft = "1.19.2"
quilt = "0.20.0-beta.4"
